services:
  balancer:
    build:
      context: ./module-balancer
      dockerfile: ./Dockerfile
    container_name: balancer
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://balancer:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3                                                                                                                                                                                                                                                 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - service-network

  registry:
    build:
      context: ./module-registry
      dockerfile: ./Dockerfile
    container_name: registry
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://registry:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - service-network
    depends_on:
      - redis

  monitoring:
    build:
      context: ./module-monitoring
      dockerfile: ./Dockerfile
    container_name: module-monitoring
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://monitoring:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - service-network
    depends_on:
      - redis

  test-client:
    build:
      context: ./test-client
      dockerfile: ./Dockerfile
    environment:
      - TARGET_URL=http://registry:8080/heartbeat
      - INTERVAL=1
    restart: unless-stopped
    networks:
      - service-network
    depends_on:
      - registry
    deploy:
      replicas: 30

  # test-client-less:
  #   build:
  #     context: ./test-client
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - TARGET_URL=http://registry:8080/heartbeat
  #     - INTERVAL=1
  #   restart: unless-stopped
  #   deploy:
  #     replicas: 3
  #     resources:
  #       limits:
  #         cpus: '0.1'  # Guaranteed minimum CPU
  #         memory: 64M  # Guaranteed minimum RAM
  #   networks:
  #     - service-network
  #   depends_on:
  #     - registry

  redis:
    image: redis:8.8-m03-trixie
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - service-network

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - './prometheus/:/etc/prometheus/'
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - service-network

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "./grafana/datasources:/etc/grafana/provisioning/datasources:ro"
      - "./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 -O- http://grafana:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - service-network
    depends_on:
      - prometheus

volumes:
  redis-data:

networks:
  service-network:
    driver: bridge
