version: "3.9"

name: "smart-balancer-go"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:8080 # Внешний порт Traefik
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - service-network

  balancer1:
    build:
      context: ./module-balancer
      dockerfile: ./Dockerfile
    container_name: module_balancer_1
    environment:
      - CONTAINER_NODE_NAME=node_1
      - REDIS_ADDR=redis:6379                                                                                                                                                                                                                                              
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webapp.entrypoints=web"
      # ВАЖНО: порт, который слушает микросервис внутри своего контейнера
      - "traefik.http.services.webapp.loadbalancer.server.port=8080" 
    networks:
      - service-network
    depends_on:
      redis:
        condition: service_healthy

  balancer2:
    build:
      context: ./module-balancer
      dockerfile: ./Dockerfile
    container_name: module_balancer_2
    environment:
      - CONTAINER_NODE_NAME=node_2
      - REDIS_ADDR=redis:6379                                                                                                                                                                                                                                              
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webapp.entrypoints=web"
      # ВАЖНО: порт, который слушает микросервис внутри своего контейнера
      - "traefik.http.services.webapp.loadbalancer.server.port=8080" 
    networks:
      - service-network
    depends_on:
      redis:
        condition: service_healthy

  balancer3:
    build:
      context: ./module-balancer
      dockerfile: ./Dockerfile
    container_name: module_balancer_3
    environment:
      - CONTAINER_NODE_NAME=node_3
      - REDIS_ADDR=redis:6379                                                                                                                                                                                                                                              
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webapp.entrypoints=web"
      # ВАЖНО: порт, который слушает микросервис внутри своего контейнера
      - "traefik.http.services.webapp.loadbalancer.server.port=8080" 
    networks:
      - service-network
    depends_on:
      redis:
        condition: service_healthy

  registry:
    build:
      context: ./module-registry
      dockerfile: ./Dockerfile
    container_name: registry
    environment:
      - REDIS_ADDR=redis:6379
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://registry:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - service-network
    depends_on:
      redis:
        condition: service_healthy

  monitoring:
    build:
      context: ./module-monitoring
      dockerfile: ./Dockerfile
    container_name: module-monitoring
    environment:
      - REDIS_ADDR=redis:6379
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - service-network
    depends_on:
      redis:
        condition: service_healthy

  test-microservice:
    build:
      context: ./test-client
      dockerfile: ./Dockerfile
    environment:
      - TARGET_URL=http://registry:8080/heartbeat
      - INTERVAL=1
    networks:
      - service-network
    deploy:
      replicas: 23

  redis:
    image: redis:8.8-m03-alpine3.23
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 15s
      retries: 60        # Ждать до 5 * 60 = 300 секунд (5 минут)
      start_period: 10s
    networks:
      - service-network

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - './prometheus/:/etc/prometheus/'
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    environment:
      TZ: "Europe/Moscow"
    networks:
      - service-network

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "./grafana/datasources:/etc/grafana/provisioning/datasources:ro"
      - "./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - service-network
    depends_on:
      - prometheus

volumes:
  redis-data:

networks:
  service-network:
    driver: bridge
